# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Inter1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 198)
        MainWindow.setMaximumSize(QtCore.QSize(522, 198))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255)")
        MainWindow.setIconSize(QtCore.QSize(4, 4))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 571, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.vamos = QtWidgets.QRadioButton(self.centralwidget)
        self.vamos.setGeometry(QtCore.QRect(240, 110, 111, 51))
        self.vamos.setObjectName("vamos")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 20, 141, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/Imagens Projeto/copy_of_ibge.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.iniciar = QtWidgets.QPushButton(self.centralwidget)
        self.iniciar.setGeometry(QtCore.QRect(120, 130, 91, 23))
        self.iniciar.setObjectName("iniciar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 522, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Bem vindo ao estudo sobre a taxa de alfabetização no brasil!"))
        self.vamos.setText(_translate("MainWindow", "Vamos!!!"))
        self.iniciar.setText(_translate("MainWindow", "iniciar"))
import iconss_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
